my_buckwheat_bot_promo = [
        "AgACAgIAAxkBAAJGb2RrvyWEqa4x-fxZVNTnUZoneqzaAAKUyTEbvwABWUttUSRiDdfwhAEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGcWRrvzFe0F6f-swyzBtsItTfGNSFAAKWyTEbvwABWUtZj-MmGKZTDgEAAwIAA3gAAy8E",
        "AgACAgIAAxkBAAJGc2Rrvzd2dn9rV0IG6BQpGRuJCz28AAKXyTEbvwABWUvygMy46O1SLQEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGdWRrv0E4vl5_ar_GzdWnFUq2W0_fAAKYyTEbvwABWUsORmcWkLzcLAEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGd2Rrv0aDN8aUH19PN9kwLdO0r-A0AAKZyTEbvwABWUvZDLmIEmhvdQEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGeWRrv0sRz34jVg9eM0U5VBxvXu5-AAKayTEbvwABWUuCD0MzEptYMgEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGe2Rrv1G95ytrNeirP3BSwCCcBskOAAKbyTEbvwABWUvxOWq6csatxQEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGfWRrv2M_nNjM_j8Ta0MQ86Dd32f6AAKcyTEbvwABWUvY5JUc_Mm6qwEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGf2Rrv2lbGwXjQ6cV0MKsgsOJ7WrZAAKdyTEbvwABWUvA6jdpIwS3hAEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGgWRrv2wnbu6reFtZq0RvRck-SrqNAAKeyTEbvwABWUvLx1S1oQqokAEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGg2Rrv3GXU_ijgTKJExF7Y8dYGJYmAAKfyTEbvwABWUvdJdeJxynYQgEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGhWRrv3QYaCKtMAVZK5ApuJFKEJi5AAKgyTEbvwABWUvvxGzzkBWf4AEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGh2Rrv3hyhR_dBHAjdO_pHBSLMkIRAAKhyTEbvwABWUuVJiTd8BByvAEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGiWRrv3wMQPsUeuHCNXlBxAungpRXAAKiyTEbvwABWUtYoUTZasa5NAEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGi2Rrv4HWBT1om5rUyR72WO238i3vAAKjyTEbvwABWUt59-5NaYpL6AEAAwIAA3kAAy8E"
    ]

akira_matchbot_promo = [
    "AgACAgIAAxkBAAJSiGS1EkCVgiX0aQhyPMmYpIdHaap5AAJvyDEbAdGoSXdWNw0YNn8JAQADAgADeQADLwQ",
    "AgACAgIAAxkBAAJSimS1EkQSjvi17wneNPz5MNMF-FZQAAJ1yDEbAdGoSV5c4j5YsDFmAQADAgADeAADLwQ",
    "AgACAgIAAxkBAAJSjGS1EkYcLpDEl3rvd9WdZ3fn8D16AAJ2yDEbAdGoST9vGHNvPVRHAQADAgADeQADLwQ",
    "AgACAgIAAxkBAAJSjmS1Ekk5atTbFNxOKbV88l_Q-ZA2AAJ3yDEbAdGoSaYMhP9gPdZaAQADAgADeQADLwQ",
    "AgACAgIAAxkBAAJSkGS1EkyZbhjmEDD3bG3v4kLxGyBeAAJ4yDEbAdGoSdS5KzWmUGXBAQADAgADeQADLwQ",
    "AgACAgIAAxkBAAJSkmS1Ek-7KZqYXCziBAABNOJuXGHrdgACecgxGwHRqEkIvpXTiWcBEwEAAwIAA3kAAy8E",
    "AgACAgIAAxkBAAJSlGS1ElLpGG366USPPg7l0IfmyLlnAAJ6yDEbAdGoSdsnzqbTPTQ4AQADAgADeQADLwQ",
    "AgACAgIAAxkBAAJSlmS1ElWYbc6DfNzjM1Icq9-XsRo-AAJ7yDEbAdGoSZ-n1VlJ6STZAQADAgADeQADLwQ",
    "AgACAgIAAxkBAAJSmGS1EliW7HNVqYm9ZrjoL9Ye6LB0AAJ8yDEbAdGoSQ0g6GnHrASxAQADAgADeQADLwQ",
    "AgACAgIAAxkBAAJSmmS1ElpNsczqM8D4m7ekyg6rBGngAAJ9yDEbAdGoSYNF6bS2_bQhAQADAgADeQADLwQ",
    "AgACAgIAAxkBAAJSnGS1El25m_Pdf9IZFSgvp19_s09zAAJ-yDEbAdGoSfQokkVpt9kOAQADAgADeQADLwQ",
    "AgACAgIAAxkBAAJSnmS1EmJ3BpB6Fn-3WUAuF3cmrmQsAAJ_yDEbAdGoSS4r6eN_QfhbAQADAgADeQADLwQ",
    "AgACAgIAAxkBAAJSoGS1EmZsZ_-104jpzX15dII-977kAAKAyDEbAdGoSaYH3O6P5UugAQADAgADeQADLwQ",
    "AgACAgIAAxkBAAJSomS1Eml78LWu_-Tuqg825AEpSIvbAAKByDEbAdGoSeY3f8k2m-9hAQADAgADeQADLwQ",
    "AgACAgIAAxkBAAJSpGS1EmzbXO4qkDCJD912pGtfLNJAAAKCyDEbAdGoSQiABfOBGfL_AQADAgADeQADLwQ"
]
