my_buckwheat_bot_promo = [
        "AgACAgIAAxkBAAJGb2RrvyWEqa4x-fxZVNTnUZoneqzaAAKUyTEbvwABWUttUSRiDdfwhAEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGcWRrvzFe0F6f-swyzBtsItTfGNSFAAKWyTEbvwABWUtZj-MmGKZTDgEAAwIAA3gAAy8E",
        "AgACAgIAAxkBAAJGc2Rrvzd2dn9rV0IG6BQpGRuJCz28AAKXyTEbvwABWUvygMy46O1SLQEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGdWRrv0E4vl5_ar_GzdWnFUq2W0_fAAKYyTEbvwABWUsORmcWkLzcLAEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGd2Rrv0aDN8aUH19PN9kwLdO0r-A0AAKZyTEbvwABWUvZDLmIEmhvdQEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGeWRrv0sRz34jVg9eM0U5VBxvXu5-AAKayTEbvwABWUuCD0MzEptYMgEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGe2Rrv1G95ytrNeirP3BSwCCcBskOAAKbyTEbvwABWUvxOWq6csatxQEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGfWRrv2M_nNjM_j8Ta0MQ86Dd32f6AAKcyTEbvwABWUvY5JUc_Mm6qwEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGf2Rrv2lbGwXjQ6cV0MKsgsOJ7WrZAAKdyTEbvwABWUvA6jdpIwS3hAEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGgWRrv2wnbu6reFtZq0RvRck-SrqNAAKeyTEbvwABWUvLx1S1oQqokAEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGg2Rrv3GXU_ijgTKJExF7Y8dYGJYmAAKfyTEbvwABWUvdJdeJxynYQgEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGhWRrv3QYaCKtMAVZK5ApuJFKEJi5AAKgyTEbvwABWUvvxGzzkBWf4AEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGh2Rrv3hyhR_dBHAjdO_pHBSLMkIRAAKhyTEbvwABWUuVJiTd8BByvAEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGiWRrv3wMQPsUeuHCNXlBxAungpRXAAKiyTEbvwABWUtYoUTZasa5NAEAAwIAA3kAAy8E",
        "AgACAgIAAxkBAAJGi2Rrv4HWBT1om5rUyR72WO238i3vAAKjyTEbvwABWUt59-5NaYpL6AEAAwIAA3kAAy8E"
    ]

akira_matchbot_promo = [
    "AgACAgIAAxkBAAIQEGS6kttzc_bdQKIqLoUCJhc7jGOoAAJtzTEbrZPYSfpFCQnl3Tp-AQADAgADeQADLwQ",
    "AgACAgIAAxkBAAIQEmS6kt_pcrGO_0tLU2igl5bqduyWAAJuzTEbrZPYSbqiv71MhItNAQADAgADeAADLwQ",
    "AgACAgIAAxkBAAIQFGS6kwXWoE-q092eLFdKyzxgbt57AAJvzTEbrZPYSQyOwaPYvYevAQADAgADeQADLwQ",
    "AgACAgIAAxkBAAIQFmS6kxSup2ddBzF-ub7krKnngNBgAAJwzTEbrZPYSYl1s8ppjXzmAQADAgADeQADLwQ",
    "AgACAgIAAxkBAAIQGGS6kyaJCktR1ptDDO5NslVkGhYOAAJxzTEbrZPYSUueTSh_2oTqAQADAgADeQADLwQ",
    "AgACAgIAAxkBAAIQGmS6kzQ_jS5KJm8hW03s2WUIsrttAAJ3zTEbrZPYSRTPJ7LNZYxvAQADAgADeQADLwQ",
    "AgACAgIAAxkBAAIQHGS6k0WG77g-iIW4864Qzx6rTKRIAAJ5zTEbrZPYSY2h7Op9vDXaAQADAgADeQADLwQ",
    "AgACAgIAAxkBAAIQHmS6k1Mwuy6ysbnP_0RJnvhXtKq5AAJ6zTEbrZPYSQABJRVGH1ZKUAEAAwIAA3kAAy8E",
    "AgACAgIAAxkBAAIQIGS6k2NseAS_MODBLb2lRK12RlV9AAJ7zTEbrZPYSTIkPyHTfqC3AQADAgADeQADLwQ",
    "AgACAgIAAxkBAAIQImS6k28yrgrm5jwNde8XKZez7NSPAAJ-zTEbrZPYSWnc4wfkqhDLAQADAgADeQADLwQ",
    "AgACAgIAAxkBAAIQJGS6k30dKLoNZBxijVg_ROqcNwr9AAJ_zTEbrZPYSd-xPjNR3cRJAQADAgADeQADLwQ",
    "AgACAgIAAxkBAAIQJmS6k4vlSCTjTGYGldvf5RmYwhWDAAKBzTEbrZPYSfp3RY-sBXFfAQADAgADeQADLwQ",
    "AgACAgIAAxkBAAIQKGS6k5r8bKPWTlxT_MlwcQJBGzASAAKCzTEbrZPYSUvAtjbhT-aBAQADAgADeQADLwQ",
    "AgACAgIAAxkBAAIQKmS6k6aPm_O2_UfKxNEBJGGpr_yIAAKFzTEbrZPYSSAzvPZfdI2dAQADAgADeQADLwQ",
    "AgACAgIAAxkBAAIQLGS6k7HlRx70IHd2ZOQu4f2Ess4GAAKJzTEbrZPYSdXRtsJ6f7ZGAQADAgADeQADLwQ"
]
